version: '3'
services:
  web:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - pizza-db
  pizza-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=pizza
      - POSTGRES_PASSWORD=111wdr
